// <auto-generated />
using ExamenAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenAPI.Migrations
{
    [DbContext(typeof(SimulationDbContext))]
    [Migration("20260711035801_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ExamenAPI.Entities.SimulationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BalanceFinal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DepositoInicial")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InteresTotal")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlazoEnAños")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TasaInteresAnual")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Simulations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
